services:
  http-es-server:
    build:
      dockerfile: dev.Dockerfile
      context: .
    networks:
      - http-es-network
    ports:
      - "8080:8080"
      - "8081:8081"
    expose:
      - "8080"
      - "8081"
    volumes:
      - .:/app
    env_file:
      - .env

  http-es-jaeger:
    container_name: http-es-jaeger
    image: jaegertracing/all-in-one
    networks:
      - http-es-network
    ports:
      - "4317:4317"
      - "16686:16686"
    environment:
      - COLLECTOR_OTLP_ENABLED=true

networks:
  http-es-network:
    driver: bridge
