app:
  name: yokai-es-app
  version: 0.1.0
modules:
  core:
    server:
      address: ":8081"
      dashboard:
        enabled: true
        overview:
          app_env: true
          app_debug: true
          app_version: true
          log_level: true
          log_output: true
          trace_sampler: true
          trace_processor: true
      metrics:
        expose: true
        collect:
          enabled: true
        normalize:
          request_path: true
          response_status: true
      healthcheck:
        startup:
          expose: true
        readiness:
          expose: true
        liveness:
          expose: true
      debug:
        config:
          expose: true
        pprof:
          expose: true
        routes:
          expose: true
        stats:
          expose: true
        build:
          expose: true
        modules:
          expose: true
  http:
    client:
      timeout: 30                            # in seconds, 30 by default
      log:
        request:
          enabled: true                      # to log request details, disabled by default
          body: false                         # to add request body to request details, disabled by default
          level: info                        # log level for request logging
        response:
          enabled: true                      # to log response details, disabled by default
          body: false                         # to add response body to request details, disabled by default
          level: info                        # log level for response logging
          level_from_response: true          # to use response code for response logging
      trace:
        enabled: true                        # to trace http calls, disabled by default
      metrics:
        collect:
          enabled: true                      # to collect http client metrics
        normalize:
          request_path: true                 # to normalize http request path, disabled by default
          response_status: true
    server:
      address: ":8080"
      trace:
        enabled: true
      metrics:
        collect:
          enabled: true
        normalize:
          request_path: true
          response_status: true
  log:
    level: info
    output: stdout
  trace:
    processor:
      type: otlp-grpc
      options:
        host: ${OTLP_COLLECTOR_HOST}:${OTLP_COLLECTOR_PORT}
  elastic:
    cloud_id: ${ELASTICSEARCH_CLOUD_ID}
    api_key: ${ELASTICSEARCH_API_KEY}
